/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dev.nizarfadlan.tugas4;

import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.Date;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MyWindows10
 */
public class PraresForm extends javax.swing.JFrame {

    /**
     * Creates new form PraresForm
     */
    public PraresForm() throws ClassNotFoundException, SQLException {
        initComponents();
        db.connection();
        bacaTabel();
        this.setTitle("211054003 - Nizar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    buttonGroup1 = new javax.swing.ButtonGroup();
    jPanel3 = new javax.swing.JPanel();
    jScrollPane2 = new javax.swing.JScrollPane();
    jTable1 = new javax.swing.JTable();
    jLabel1 = new javax.swing.JLabel();
    fieldNIM = new javax.swing.JTextField();
    buttonSubmit = new javax.swing.JButton();
    jLabel2 = new javax.swing.JLabel();
    fieldNama = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    pilihLaki = new javax.swing.JRadioButton();
    pilihPerempuan = new javax.swing.JRadioButton();
    jLabel4 = new javax.swing.JLabel();
    fieldTempatLahir = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    fieldNoHP = new javax.swing.JTextField();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTextArea1 = new javax.swing.JTextArea();
    jLabel8 = new javax.swing.JLabel();
    fieldTanggalLahir = new com.toedter.calendar.JDateChooser();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel3.setBackground(java.awt.Color.white);

    jTable1.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "NIM", "Nama", "Jenis Kelamin", "TTL", "Alamat", "Nomer Handphone"
      }
    ) {
      Class[] types = new Class [] {
        java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
      };
      boolean[] canEdit = new boolean [] {
        false, false, false, false, false, false
      };

      public Class getColumnClass(int columnIndex) {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mousePressed(java.awt.event.MouseEvent evt) {
        jTable1MousePressed(evt);
      }
    });
    jScrollPane2.setViewportView(jTable1);

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 856, Short.MAX_VALUE)
        .addContainerGap())
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane2)
        .addContainerGap())
    );

    jLabel1.setText("NIM");

    buttonSubmit.setText("Submit");
    buttonSubmit.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        buttonSubmitActionPerformed(evt);
      }
    });

    jLabel2.setText("Nama");

    jLabel3.setText("Jenis Kelamin");

    buttonGroup1.add(pilihLaki);
    pilihLaki.setSelected(true);
    pilihLaki.setText("Laki-Laki");

    buttonGroup1.add(pilihPerempuan);
    pilihPerempuan.setText("Perempuan");

    jLabel4.setText("Tempat Lahir");

    jLabel5.setText("Tanggal Lahir");

    jLabel6.setText("Alamat");

    jTextArea1.setColumns(20);
    jTextArea1.setRows(5);
    jScrollPane1.setViewportView(jTextArea1);

    jLabel8.setText("Nomer Handphone");

    jButton1.setText("Clear");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    jButton2.setText("Delete");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addGap(19, 19, 19)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel8)
              .addComponent(jLabel6)
              .addComponent(jLabel5)
              .addComponent(jLabel3)
              .addComponent(jLabel2)
              .addComponent(jLabel1)
              .addComponent(pilihLaki)
              .addComponent(pilihPerempuan)
              .addComponent(jLabel4)
              .addComponent(fieldNIM, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
            .addGap(12, 12, 12))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addComponent(fieldTanggalLahir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(fieldNama, javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(fieldTempatLahir, javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
              .addComponent(fieldNoHP, javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(buttonSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(22, 22, 22)
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(fieldNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(jLabel2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(fieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(jLabel3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(pilihLaki)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(pilihPerempuan)
        .addGap(18, 18, 18)
        .addComponent(jLabel4)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(fieldTempatLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(jLabel5)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(fieldTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(8, 8, 8)
        .addComponent(jLabel6)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(jLabel8)
        .addGap(18, 18, 18)
        .addComponent(fieldNoHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(buttonSubmit)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jButton1)
          .addComponent(jButton2))
        .addContainerGap(18, Short.MAX_VALUE))
      .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void newRecord() {
        fieldNIM.setText("");
        fieldNIM.setEditable(true);
        fieldNama.setText("");
        fieldTempatLahir.setText("");
        jTextArea1.setText("");
        fieldNoHP.setText("");
        NIMSelected = null;
    }
    
    private void editData() {
      try {
            prestt = db.conn.prepareStatement("SELECT * FROM mahasiswa WHERE nim = ? LIMIT 1");
            prestt.setString(1, NIMSelected);
            ResultSet res = prestt.executeQuery();
            
            while (res.next()) {
              String jk = res.getString("jenis_kelamin");
              pilihLaki.setSelected("L".equals(jk));
              pilihPerempuan.setSelected("P".equals(jk));
              
              fieldNIM.setText(res.getString("nim"));
              fieldNama.setText(res.getString("nama"));
              fieldTempatLahir.setText(res.getString("tempat_lahir"));
              fieldTanggalLahir.setDate(res.getDate("tanggal_lahir"));
              jTextArea1.setText(res.getString("alamat"));
              fieldNoHP.setText(res.getString("nomer_hp"));
              
              fieldNIM.setEditable(false);
            }

            prestt.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    private boolean deleteData() {
        try {
            prestt = db.conn.prepareStatement("DELETE FROM mahasiswa WHERE nim = ?");
            prestt.setString(1, NIMSelected);
            int res = prestt.executeUpdate();
            prestt.close();
            
            return res == 1;
        } catch (SQLException ex) {
            ex.printStackTrace();
            return false;
        }
    }
    
    private boolean checkNIMExist(String nim) {
        try {
            prestt = db.conn.prepareStatement("SELECT * FROM mahasiswa WHERE nim = ? LIMIT 1");
            prestt.setString(1, nim);
            ResultSet res = prestt.executeQuery();
            prestt.close();
            
            return !res.isBeforeFirst();
        } catch (SQLException ex) {
            ex.printStackTrace();
            return false;
        }
    }
    
    private void bacaTabel() {
        try {
            stmt = db.openConnection();
            ResultSet res = stmt.executeQuery("SELECT * FROM mahasiswa");
            DefaultTableModel modelTable = (DefaultTableModel) jTable1.getModel();
            modelTable.setRowCount(0);
            while (res.next()) {
                String nim = res.getString("nim");
                String nama = res.getString("nama");
                String jk = res.getString("jenis_kelamin");
                String tempat_l = res.getString("tempat_lahir");
                String tanggal_l = res.getDate("tanggal_lahir").toString();
                String alamat = res.getString("alamat");
                String nomer_hp = res.getString("nomer_hp");
                
                String ttl = tempat_l + ", " + tanggal_l;
                
                String[] dataListTemp = {nim, nama, jk, ttl, alamat, nomer_hp};
                modelTable.addRow(dataListTemp);
            }

            stmt.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    private void buttonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubmitActionPerformed
        String nim = fieldNIM.getText();
        
        if (!checkNIMExist(nim) || NIMSelected != null) {
          try {
              String nama = fieldNama.getText();
              String jenisKelamin = pilihLaki.isSelected() ? "L" : "P";
              String tempatLahir = fieldTempatLahir.getText();
              String tanggalLahir = String.valueOf(fm.format(fieldTanggalLahir.getDate()));
              String alamat = jTextArea1.getText();
              String nomerHp = fieldNoHP.getText();

              if (NIMSelected != null) {
                prestt = db.conn.prepareStatement(
                        "UPDATE mahasiswa SET nama = ?, jenis_kelamin = ?, tempat_lahir = ?, tanggal_lahir = ?, alamat = ?, nomer_hp = ? WHERE nim = ?"
                );

                prestt.setString(1, nama);
                prestt.setString(2, jenisKelamin);
                prestt.setString(3, tempatLahir);
                prestt.setDate(4, Date.valueOf(tanggalLahir));
                prestt.setString(5, alamat);
                prestt.setString(6, nomerHp);
                prestt.setString(7, NIMSelected);
              } else {
                prestt = db.conn.prepareStatement("INSERT INTO mahasiswa VALUES(?,?,?,?,?,?,?)");
                prestt.setString(1, nim);
                prestt.setString(2, nama);
                prestt.setString(3, jenisKelamin);
                prestt.setString(4, tempatLahir);
                prestt.setDate(5, Date.valueOf(tanggalLahir));
                prestt.setString(6, alamat);
                prestt.setString(7, nomerHp);
              }

              int res = prestt.executeUpdate();
              
              if (res == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil " + (NIMSelected != null ? "diubah" : "ditambah"), "Berhasil",JOptionPane.INFORMATION_MESSAGE);
              } else {
                JOptionPane.showMessageDialog(this, "Data gagal " + (NIMSelected != null ? "diubah" : "ditambah"), "Gagal",JOptionPane.ERROR_MESSAGE);
              }
              
              prestt.close();
          } catch (SQLException e) {
              e.printStackTrace();
          }
        } else {
          JOptionPane.showMessageDialog(this, "Data sudah ada", "Gagal",JOptionPane.ERROR_MESSAGE);
        }
        
        NIMSelected = null;
        newRecord();
        bacaTabel();
    }//GEN-LAST:event_buttonSubmitActionPerformed

  private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
    int row = jTable1.getSelectedRow();
    NIMSelected = (String) jTable1.getValueAt(row, 0);
    if (NIMSelected != null) editData();
  }//GEN-LAST:event_jTable1MousePressed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    newRecord();
  }//GEN-LAST:event_jButton1ActionPerformed

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    if (NIMSelected != null) {
      boolean result = deleteData();
      
      if (result) {
        NIMSelected = null;
        JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Berhasil",JOptionPane.INFORMATION_MESSAGE);
      } else {
        JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal",JOptionPane.ERROR_MESSAGE);
      }
    } else {
      JOptionPane.showMessageDialog(this, "Belum ada data yang dipilih", "Gagal",JOptionPane.ERROR_MESSAGE);
    }
    
    newRecord();
    bacaTabel();
  }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PraresForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PraresForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PraresForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PraresForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new PraresForm().setVisible(true);
                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(PraresForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
  String format = "yyyy-MM-dd";
  SimpleDateFormat fm = new SimpleDateFormat(format);
  DBConnection db = new DBConnection();

  private Statement stmt;
  private PreparedStatement prestt;

  private String NIMSelected = null;

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.ButtonGroup buttonGroup1;
  private javax.swing.JButton buttonSubmit;
  private javax.swing.JTextField fieldNIM;
  private javax.swing.JTextField fieldNama;
  private javax.swing.JTextField fieldNoHP;
  private com.toedter.calendar.JDateChooser fieldTanggalLahir;
  private javax.swing.JTextField fieldTempatLahir;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JTable jTable1;
  private javax.swing.JTextArea jTextArea1;
  private javax.swing.JRadioButton pilihLaki;
  private javax.swing.JRadioButton pilihPerempuan;
  // End of variables declaration//GEN-END:variables
}
